### ISSUE TITLE
establish continuity of government

### ISSUE THREAD

**Issue by pirog** [kalamuna/playbox#47]
Create a continuity of government feature. `playbox_emergency`. 

1. This will contain a Vice President content type modeled exactly after the President content type. 
2. On the President content type you will add a "Running Mate" entity reference field 
3. Using the Homeland Security API whenever the threat level is high or very high all the Presidents on the site are swapped out for their VPs.

**Comment by litwol** [comment]
done. See pull request.

My solution is based on overriding views result to display VP info instead of president's when threat level is considered elevated. Solution is "hackish", but works. With more time and resources i would prefer to split theming logic (battle page, etc) from content retrieval logic (views query tightly coupled to pres-loading, robot loading, theming overrides, voting logic, etc).
