### ISSUE TITLE
Show the winner when the winner is declared!

### ISSUE THREAD

**Issue by pirog** [kalamuna/playbox#75]
Issue #35 correctly provided the backend functionality to assign a winner when the winner reaches that total but now we need to reflect that on the front end:

- [ ] When a winner is declared the user should not be able to use ajax to add more votes
- [ ] When a winner it declared some sort of CSS magic should indicate the winner and the loser clearly. 

This should probably all happen in the same files and ajax calls in #35

**Comment by oneorangecat** [comment]
Howdy. I had a bit of time today so have implemented these few bits in branch 75-declare-winner. I included some rather excessive extra work, mostly to handle the now "bad" data in the system (due to extra voting past the win point) - didn't want to assume the last selected contender is actually the winner and has exactly the right number of votes though, and it's all good fun :)
Front end work not my strongest area but I realise that the whole Battles/Home page content is skewed (not correctly centered on the page) - not sure if that's already raised in here but I'm happy to check and raise it if not. Haven't tried to correct that here of course, just adjusted my "win" message to fit and included a comment to that effect so the css can be removed when appropriate. Cheers!

**Comment by pirog** [comment]
The only thing that could make this resolution better is if we could somehow get Donald Trump to designate the winner/loser of the battle. Going to spin up a new ticket for that.

**Comment by oneorangecat** [comment]
I LIKE THIS :)

 

On Oct 3, 2015, at 15:12, Mike Pirog <notifications@github.com> wrote:

The only thing that could make this resolution better is if we could somehow get Donald Trump to designate the winner/loser of the battle. Going to spin up a new ticket for that.
